"""Raw GeNN weight-update model definitions for e-prop and its variants.

Each model here is a single, self-contained GeNN WUM dict - no commented-out
alternatives living inside the same string. To pick one at compile time, use
`get_hidden_model`, `get_output_model`, or `get_feedback_model` below with the
enums from `.variants`.
"""

from copy import deepcopy
from pygenn import VarAccess, CustomUpdateVarAccess

from .variants import HiddenRule, OutputRule, FeedbackRule


# ============================================================================
# Hidden-layer (recurrent) eligibility-trace models
# ============================================================================

_EPROP_LIF_PERT = {
    "params": [("CReg", "scalar"), ("Alpha", "scalar"),
               ("FTarget", "scalar"), ("AlphaFAv", "scalar"),
               ("Vthresh_post", "scalar")],
    "vars": [("g", "scalar", VarAccess.READ_ONLY),
             ("eFiltered", "scalar"), ("DeltaG", "scalar"),
             ("NoiseTrace", "scalar"), ("RLNoiseTrace", "scalar")],
    "pre_vars": [("ZFilter", "scalar")],
    "post_vars": [("Psi", "scalar"), ("FAvg", "scalar")],
    "post_neuron_var_refs": [("RefracTime_post", "scalar"), ("V_post", "scalar"),
                             ("E_post", "scalar"), ("Ebase_post", "scalar"),
                             ("Noise", "scalar")],

    "pre_spike_code": "ZFilter += 1.0;",
    "pre_dynamics_code": "ZFilter *= Alpha;",

    "post_spike_code": "FAvg += (1.0 - AlphaFAv);",
    "post_dynamics_code": """
    FAvg *= AlphaFAv;
    if (RefracTime_post > 0.0) {
      Psi = 0.0;
    }
    else {
      Psi = (1.0 / Vthresh_post) * 0.3 * fmax(0.0, 1.0 - fabs((V_post - Vthresh_post) / Vthresh_post));
    }
    """,

    "pre_spike_syn_code": """
    scalar eps = 0.01 * Noise;
    addToPost(g + eps);
    NoiseTrace += eps;
    """,

    "synapse_dynamics_code": """
    const scalar e = ZFilter * Psi;
    scalar eF = eFiltered;
    eF = (eF * Alpha) + e;

    DeltaG += 0.0 * (eF * E_post) + ((FAvg - FTarget) * CReg * e) + e * NoiseTrace * fabs(E_post);

    NoiseTrace *= Alpha;
    eFiltered = eF;
    """}

_EPROP_ALIF = {
    "params": [("CReg", "scalar"), ("Alpha", "scalar"), ("Rho", "scalar"),
               ("FTarget", "scalar"), ("AlphaFAv", "scalar"),
               ("Vthresh_post", "scalar"), ("Beta_post", "scalar")],
    "vars": [("g", "scalar", VarAccess.READ_ONLY),
             ("eFiltered", "scalar"), ("epsilonA", "scalar"),
             ("DeltaG", "scalar")],
    "pre_vars": [("ZFilter", "scalar")],
    "post_vars": [("Psi", "scalar"), ("FAvg", "scalar")],
    "post_neuron_var_refs": [("RefracTime_post", "scalar"), ("V_post", "scalar"),
                             ("A_post", "scalar"), ("E_post", "scalar")],

    "pre_spike_code": "ZFilter += 1.0;",
    "pre_dynamics_code": "ZFilter *= Alpha;",

    "post_spike_code": "FAvg += (1.0 - AlphaFAv);",
    "post_dynamics_code": """
    FAvg *= AlphaFAv;
    if (RefracTime_post > 0.0) {
      Psi = 0.0;
    }
    else {
      Psi = (1.0 / Vthresh_post) * 0.3 * fmax(0.0, 1.0 - fabs((V_post - (Vthresh_post + (Beta_post * A_post))) / Vthresh_post));
    }
    """,

    "pre_spike_syn_code": "addToPost(g);",
    "synapse_dynamics_code": """
    scalar epsA = epsilonA;
    const scalar psiZFilter = Psi * ZFilter;
    const scalar psiBetaEpsilonA = Psi * Beta_post * epsA;

    const scalar e = psiZFilter - psiBetaEpsilonA;
    epsilonA = psiZFilter + ((Rho * epsA) - psiBetaEpsilonA);

    scalar eF = eFiltered;
    eF = (eF * Alpha) + e;

    DeltaG += (eF * E_post) + ((FAvg - FTarget) * CReg * e);
    eFiltered = eF;
    """}

_HIDDEN_MODELS = {
    HiddenRule.LIF: _EPROP_LIF_PERT,
    HiddenRule.ALIF: _EPROP_ALIF,
}


def get_hidden_model(rule: HiddenRule) -> dict:
    """Return a fresh copy of a supervised hidden-layer model dict. The RL / TD(lambda) hidden rule is
    generated from a HiddenRuleConfig by :func:`.hidden_rule.build_td_hidden_model`."""
    if rule is HiddenRule.ALIF_TD_LAMBDA:
        raise ValueError("the TD(lambda) hidden rule is generated by hidden_rule.build_td_hidden_model")
    return deepcopy(_HIDDEN_MODELS[rule])


# ============================================================================
# Output (readout) models
# ============================================================================

_OUTPUT_SUPERVISED_SYMMETRIC = {
    "params": [("Alpha", "scalar")],
    "vars": [("g", "scalar", VarAccess.READ_ONLY), ("DeltaG", "scalar")],
    "pre_vars": [("ZFilter", "scalar")],
    "post_neuron_var_refs": [("E_post", "scalar")],

    "pre_spike_code": "ZFilter += 1.0;",
    "pre_dynamics_code": "ZFilter *= Alpha;",

    "pre_spike_syn_code": "addToPost(g);",
    "synapse_dynamics_code": """
    DeltaG += ZFilter * E_post;
    addToPre(g * E_post);
    """}

_OUTPUT_SUPERVISED_RANDOM = deepcopy(_OUTPUT_SUPERVISED_SYMMETRIC)
_OUTPUT_SUPERVISED_RANDOM["synapse_dynamics_code"] = "DeltaG += ZFilter * E_post;"

_OUTPUT_SUPERVISED_ADAPTIVE_FEEDBACK = deepcopy(_OUTPUT_SUPERVISED_SYMMETRIC)
del _OUTPUT_SUPERVISED_ADAPTIVE_FEEDBACK["pre_spike_syn_code"]

_OUTPUT_VALUE_SYMMETRIC = {
    "params": [("Alpha", "scalar"), ("GammaLambda", "scalar"), ("RetE", "scalar")],
    "vars": [("g", "scalar", VarAccess.READ_ONLY), ("DeltaG", "scalar"), ("RLTrace", "scalar")],
    "pre_vars": [("ZFilter", "scalar")],
    "post_neuron_var_refs": [("E_post", "scalar"), ("ValReg_post", "scalar")],

    "pre_spike_code": "ZFilter += 1.0;",
    "pre_dynamics_code": "ZFilter *= Alpha;",

    "pre_spike_syn_code": "addToPost(g);",
    "synapse_dynamics_code": """
    DeltaG += RLTrace * E_post + ZFilter * ValReg_post;
    RLTrace = GammaLambda * RLTrace - ZFilter;

    if (RetE == 0)
        addToPre(g);
    else
        addToPre(g * E_post);
    """}

_OUTPUT_VALUE_RANDOM = deepcopy(_OUTPUT_VALUE_SYMMETRIC)
_OUTPUT_VALUE_RANDOM["synapse_dynamics_code"] = """
    DeltaG += RLTrace * E_post + ZFilter * ValReg_post;
    RLTrace = GammaLambda * RLTrace - ZFilter;
"""

_OUTPUT_VALUE_ADAPTIVE_FEEDBACK = deepcopy(_OUTPUT_VALUE_SYMMETRIC)
del _OUTPUT_VALUE_ADAPTIVE_FEEDBACK["pre_spike_syn_code"]
_OUTPUT_VALUE_ADAPTIVE_FEEDBACK["post_neuron_var_refs"] += [("F_post", "scalar")]
_OUTPUT_VALUE_ADAPTIVE_FEEDBACK["synapse_dynamics_code"] = """
    DeltaG += RLTrace * E_post + ZFilter * ValReg_post;
    RLTrace = GammaLambda * RLTrace - ZFilter;

    if (RetE == 0)
        addToPre(g);
    else
        addToPre(g * F_post);
"""

_OUTPUT_POLICY_SYMMETRIC = {
    "params": [("Alpha", "scalar"), ("Lambda", "scalar")],
    "vars": [("g", "scalar", VarAccess.READ_ONLY), ("DeltaG", "scalar"), ("RLTrace", "scalar")],
    "pre_vars": [("ZFilter", "scalar")],
    "post_neuron_var_refs": [("E_post", "scalar"), ("PG_post", "scalar"), ("TdE_post", "scalar")],

    "pre_spike_code": "ZFilter += 1.0;",
    "pre_dynamics_code": "ZFilter *= Alpha;",

    "pre_spike_syn_code": "addToPost(g);",
    "synapse_dynamics_code": """
    DeltaG += TdE_post * RLTrace + ZFilter * E_post;
    RLTrace = Lambda * RLTrace + ZFilter * PG_post;

    addToPre(g * PG_post);
    """
}

_OUTPUT_POLICY_RANDOM = deepcopy(_OUTPUT_POLICY_SYMMETRIC)
_OUTPUT_POLICY_RANDOM["synapse_dynamics_code"] = """
    DeltaG += TdE_post * RLTrace + ZFilter * E_post;
    RLTrace = Lambda * RLTrace + ZFilter * PG_post;
"""

_OUTPUT_POLICY_ADAPTIVE_FEEDBACK = deepcopy(_OUTPUT_POLICY_SYMMETRIC)
del _OUTPUT_POLICY_ADAPTIVE_FEEDBACK["pre_spike_syn_code"]
_OUTPUT_POLICY_ADAPTIVE_FEEDBACK["post_neuron_var_refs"] += [("F_post", "scalar")]
_OUTPUT_POLICY_ADAPTIVE_FEEDBACK["synapse_dynamics_code"] = """
    DeltaG += TdE_post * RLTrace + ZFilter * E_post;
    RLTrace = Lambda * RLTrace + ZFilter * PG_post;

    addToPre(g * F_post);
"""

_OUTPUT_MODELS = {
    OutputRule.SUPERVISED_SYMMETRIC: _OUTPUT_SUPERVISED_SYMMETRIC,
    OutputRule.SUPERVISED_RANDOM: _OUTPUT_SUPERVISED_RANDOM,
    OutputRule.SUPERVISED_ADAPTIVE_FEEDBACK: _OUTPUT_SUPERVISED_ADAPTIVE_FEEDBACK,
    OutputRule.VALUE_SYMMETRIC: _OUTPUT_VALUE_SYMMETRIC,
    OutputRule.VALUE_RANDOM: _OUTPUT_VALUE_RANDOM,
    OutputRule.VALUE_ADAPTIVE_FEEDBACK: _OUTPUT_VALUE_ADAPTIVE_FEEDBACK,
    OutputRule.POLICY_SYMMETRIC: _OUTPUT_POLICY_SYMMETRIC,
    OutputRule.POLICY_RANDOM: _OUTPUT_POLICY_RANDOM,
    OutputRule.POLICY_ADAPTIVE_FEEDBACK: _OUTPUT_POLICY_ADAPTIVE_FEEDBACK,
}


def get_output_model(rule: OutputRule) -> dict:
    """Return a fresh copy of the output-layer model dict for `rule`."""
    return deepcopy(_OUTPUT_MODELS[rule])


# ============================================================================
# Pure feedback-connection models (conn.is_feedback == True, non-adaptive)
# ============================================================================

_FEEDBACK_RANDOM_ERROR = {
    "vars": [("g", "scalar", VarAccess.READ_ONLY)],
    "post_neuron_var_refs": [("E_post", "scalar")],
    "synapse_dynamics_code": "addToPre(g * E_post);"}

_FEEDBACK_RANDOM_PLAIN = {
    "vars": [("g", "scalar", VarAccess.READ_ONLY)],
    "post_neuron_var_refs": [("E_post", "scalar")],
    "synapse_dynamics_code": "addToPre(g);"}

_FEEDBACK_MODELS = {
    FeedbackRule.RANDOM_ERROR: _FEEDBACK_RANDOM_ERROR,
    FeedbackRule.RANDOM_PLAIN: _FEEDBACK_RANDOM_PLAIN,
    # POLICY_ADAPTIVE / VALUE_ADAPTIVE reuse the output adaptive-feedback
    # models directly, since they're the same GeNN model applied in reverse.
    FeedbackRule.POLICY_ADAPTIVE: _OUTPUT_POLICY_ADAPTIVE_FEEDBACK,
    FeedbackRule.VALUE_ADAPTIVE: _OUTPUT_VALUE_ADAPTIVE_FEEDBACK,
}


def get_feedback_model(rule: FeedbackRule) -> dict:
    """Return a fresh copy of the feedback-connection model dict for `rule`."""
    return deepcopy(_FEEDBACK_MODELS[rule])


# ============================================================================
# Custom-update models (unrelated to weight-update variant selection,
# used by every configuration)
# ============================================================================

GRADIENT_BATCH_REDUCE_MODEL = {
    "vars": [("ReducedGradient", "scalar", CustomUpdateVarAccess.REDUCE_BATCH_SUM)],
    "var_refs": [("Gradient", "scalar")],
    "update_code": """
    ReducedGradient = Gradient;
    Gradient = 0;
    """}
